# in production we won't have this application.yaml to run this so the way to run this
#with jar is
#   .\mvnw clean package -D spring.profiles.active=prod
spring:
  data:
    mongodb:
      uri: mongodb+srv://amitkumaramitkumar15351_db_user:TIArXoh3U1g0ZiDw@cluster0.onl7nf7.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true
server:
  port: 8080
  servlet:
    context-path: /journal