##spring.data.mongodb.uri:mongodb+srv://amitkumaramitkumar15351_db_user:TIArXoh3U1g0ZiDw@cluster0.onl7nf7.mongodb.net/?appName=Cluster0
##spring.data.mongodb.database=journaldb
##spring.data.mongodb.auto-index-creation=true
##in ymal we don't need to write things again and agian like spring.data.mongodb we are doing
#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://amitkumaramitkumar15351_db_user:TIArXoh3U1g0ZiDw@cluster0.onl7nf7.mongodb.net/?appName=Cluster0
#      database: journaldb
#      auto-index-creation: true
#server:
#  port: 8080
#  servlet:
#    context-path: /journal
spring:
  config:
    activate:
      on-profile: dev